# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         App-SimpleScan-Plugin-Plaintext
version:      1.01
version_from: lib/App/SimpleScan/Plugin/Plaintext.pm
installdirs:  site
requires:
    App::SimpleScan:               1
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.28
